# mkdocs.yml

# Inicializando fichero mkdocs.yml
site_name: Tarea Unidad 0 - RA5
site_description: 'Documentación de la Tarea Unidad 0 - RA5 sobre Git, Docker y CI/CD.'
site_author: 'Jonathan Barbero Sánchez'

# Estructura de navegación
nav:
  - Home: index.md
  - Git: git.md
  - GitHub Actions: gitActions.md
  - GitPages: gitPages.md
  - Docker: docker.md
  - Conclusiones: conclusiones.md

# Directorios
doc_dir: docs

# Fin del fichero makdocs.yml
