# mkdocs.yml

# Inicializando fichero mkdocs.yml
site_name: Tarea Unidad 0 - RA5

# Estructura de navegaci√≥n
nav:
  - Home: index.md
  - Git: guia_uso.md
  - GitHub Actions: gitActions.md
  - GitPages: gitPages.md
  - Docker: docker.md
  - Conclusiones: conclusiones.md

# Directorios
docs_dir: docs

# Fin del fichero mkdocs.yml
